# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gavin Lifrieri
email: gavinlifrieri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm currently a high-school senior enrolled at FLHS. I will be
  attending Harvard University in the fall of 2017 and I hope to concentrate
  in Computer Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: llcoolgreys
github_username:  CaelumTerrae

# Build settings
markdown: kramdown
